import React from 'react';

export default function UserGuide({ navigate }) {
  return <div className="guide-grid">
    <section className="card"><span className="eyebrow">GET STARTED</span><h2>Follow an incident from signal to response</h2>
      <ol className="guide-steps">
        <li><h3>Add locations and devices</h3><p>In Settings, create locations with your own names and optional addresses. Add devices with a name, room and type. Duplicate a device to create another sensor or camera. Simulation is the available connection method.</p></li>
        <li><h3>Save alerts and scenarios</h3><p>In Simulation Studio, name a single alert or a multi-device scenario. Add device signals and optional details, then save. Saving does not send an alert.</p></li>
        <li><h3>Trigger from Command Center</h3><p>Use the dropdown under the Alexa briefing to select one or several saved simulations. Choose a new or existing incident and press Send. Overlapping selections must be removed so each device sends once per batch. To add evidence later, select another saved alert and the existing incident.</p></li>
        <li><h3>Review the response</h3><p>Open Command center to inspect evidence, the saved AI assessment and policy decisions. An accepted signal may take a moment to appear.</p></li>
        <li><h3>Coordinate through Alexa+</h3><p>Select an incident and refresh context and actions. Use suggested commands to check status, read check-ins or prepare a handoff. Valve approval is tied to the displayed assessment. If it changes, refresh and review the new proposal before confirming. Clearing local chat keeps incident history.</p></li>
        <li><h3>Check in and prepare a handoff</h3><p>Household keeps reports for the selected incident. Handoff prepares a timestamped summary for review or printing.</p></li>
      </ol><button className="primary" onClick={() => navigate('simulation-lab')}>Open Simulation lab</button>
    </section>
    <div><section className="card"><h2>Understand the controls</h2>
      <details open><summary>Incidents and signals</summary><p>An incident groups related evidence. A single alert uses one device; a scenario contains up to 20 distinct devices. Combine saved definitions in Command Center; the combined batch also supports at most 20 distinct devices. No alerts are triggered from Studio.</p></details>
      <details><summary>Map colours</summary><p>Amber means evidence was recorded. Red marks recent evidence cited by a current urgent assessment, or three distinct smoke detectors reporting in the same room within five minutes. Other devices keep their own state. This simulated escalation does not establish fire size or mean the virtual siren executed.</p></details>
      <details><summary>Assessments and actions</summary><p>An assessment is the AI’s interpretation of available evidence. Policy checks determine whether a virtual action is allowed. A proposed or pending action is not a completed action; inspect the recorded result.</p></details>
      <details><summary>New evidence and decision review</summary><p>New signals advance the incident’s evidence revision. Older assessments stay in history, but cannot authorize new actions. Decision review shows the saved input, citations, uncertainties and policy reasons. You can agree or reject the current assessment; rejection blocks future execution, while agreement does not bypass device confirmation. Automatic assessment is limited to 20 signals per incident.</p></details>
      <details><summary>Check-ins</summary><p>“Reported safe” is a self-report for that incident, not verified safety. Motion does not identify people. Missing reports remain unknown.</p></details>
      <details><summary>Retries and session expiry</summary><p>After an uncertain write, refresh its saved status before retrying. The signal retry control reuses the original event. Access tokens refresh while your sign-in session remains valid.</p></details>
      <details><summary>Edit, delete and replay</summary><p>Saved simulation definitions are stored for your account and can be edited or deleted in Studio without changing incident evidence. Select a saved simulation again in Command Center to replay it. Pending deliveries stay in this tab and retry with the same event IDs; accepted signals are skipped. Batches send sequentially, not atomically. Previous browser queues can be imported as editable definitions in Studio.</p></details>
      <details><summary>Delete incident data</summary><p>In Settings → Data controls, choose an incident and type its full ID to confirm. New work is blocked immediately. Background cleanup becomes eligible after 15 minutes and runs on a five-minute schedule. Refresh cleanup status; only “completed” means active database records and all stored S3 evidence versions have been removed. Minimal replay-blocking markers remain. Backups and service history follow separate retention settings. Locations and device settings are not deleted with an incident.</p></details>
    </section><section className="card"><h2>About this workspace</h2><p>Signals and device actions are simulated. The Alexa+ page is a browser simulator. Handoff does not contact emergency services.</p><p>The shared guest account is visible to other visitors. Use fictional names and observations.</p></section></div>
  </div>;
}
