import React from 'react';

export default function UserGuide({ navigate }) {
  return <div className="guide-grid"><section className="card"><span className="eyebrow">GET STARTED</span><h2>From device signal to coordinated response</h2>
    <ol className="guide-steps">
      <li><h3>Explore Maple House</h3><p>Your three-bedroom duplex has 19 fixed rooms and areas with 37 simulated safety/security devices. Settings lets you add, edit or remove devices. Select an existing room from the dropdown; the house layout stays in place.</p></li>
      <li><h3>Define a simulation</h3><p>In Simulation Studio save a single alert or scenario. Select its initial alarm/connectivity, reporting mode, duration and optional final clear. Saving never triggers an alert.</p></li>
      <li><h3>Start from the map</h3><p>Open Command Center from the navigation. Select saved definitions or click a mapped device. Overlap warnings name conflicting definitions. Send schedules a cloud run; it does not mean every signal is published yet. Run status shows expected and published counts.</p></li>
      <li><h3>Let incident coordination run</h3><p>Automatic assignment creates a named incident or joins a related open incident in Maple House. Unrelated hazards remain separate. Accepted signals share the ingestion, assessment and policy pipeline.</p></li>
      <li><h3>Return to live assistance</h3><p>Alexa+ is the home view: briefings and active signals refresh automatically. Ask about the incident in the adjacent conversation panel. Click a signal to locate its device on the map. Spoken updates require this page to remain open. Device response controls are not enabled.</p></li>
      <li><h3>Review and resolve</h3><p>History keeps evidence, decisions, notes and old reports. Resolve explicitly closes an incident and cancels associated future generation. A new fresh alert can create a new incident with a fresh simulation allowance.</p></li>
    </ol><button className="primary" onClick={() => navigate('settings')}>Open Settings</button></section>
    <section className="card"><h2>Controls and limits</h2>
      <details open><summary>State, repeats and clear</summary><p>On-change emits the configured state once. Repeat emits active reports at 60–900 second intervals for up to an hour; an optional final clear is separate. The minute-tick worker can deliver late under load, retaining scheduled timestamps. Stop does not clear an alarm. Paused runs may still owe a clear.</p></details>
      <details><summary>Capacity and allowance</summary><p>200 devices in Maple House, up to 30 devices per room; 250 saved definitions and 2,000 total signal references. One run selects at most 200 distinct devices. Each incident starts with 2,000 reserved simulation signals, extendable deliberately to 10,000. Retries spend once. Exhaustion pauses generation, not the incident or processing of accepted evidence.</p></details>
      <details><summary>Retries and cloud runs</summary><p>Run state persists when the tab closes. Resume reuses pending event identities. Stop releases device ownership; one in-flight delivery may complete. A device cannot belong to overlapping active runs. Existing tab-local pending batches remain retryable for migration.</p></details>
      <details><summary>Map colours and decisions</summary><p>Doorbell, ordinary motion, package, vehicle, person detection and normal contact-open are notification-only. Water, weather, freeze, power and tamper signals are warnings. Red means CO, gas, medical SOS, security alarm, forced entry or glass break; smoke/heat turns red only when distinct fire/gas devices corroborate in one room, or a current validated assessment raises urgency. Repeating one device is not independent corroboration. An urgent indication is not proof of fire size. Proposed, pending, failed and successful virtual actions are distinct.</p></details>
      <details><summary>Fresh evidence and assessments</summary><p>New signals can make an earlier assessment stale. The pipeline reassesses changed evidence; the briefing distinguishes current findings from pending assessment. Historical action records are read-only. No device action is performed by this interface.</p></details>
      <details><summary>Speech and privacy</summary><p>Speech needs an open browser and permission; microphone support varies. English transcription uses the browser speech service. Questions send automatically when you finish speaking; Cancel listening stops capture. Voice questions are read-only. Text is always available. Ask Alexa+ retains 20 replies per incident in this browser for up to 7 days; sign out or Clear removes them. Earlier answers reflect evidence at the time, not necessarily current conditions.</p></details>
      <details><summary>Edit and delete</summary><p>Settings manages devices in the fixed house. Studio edits/removes reusable definitions without deleting past evidence. Data controls request incident deletion after exact confirmation. A 15-minute drain window precedes scheduled cleanup of records, related runs and all evidence object versions. Only completed means cleaned; minimal replay markers remain. Backups and service history follow separate retention.</p></details>
      <details><summary>Access and safety</summary><p>Sign-in persists in this browser for up to 24 hours, including reopening a tab, with automatic short-lived token refresh. Sign out on shared computers. Revocation, cleared browser storage or expiry requires sign-in again. The shared guest account is visible to other visitors: use synthetic data only. This is an incident-coordination prototype, not a safety-certified alarm or emergency service. Follow official alarms and emergency guidance.</p></details>
    </section></div>;
}
