import React from 'react';

export default function UserGuide({ navigate }) {
  return <div className="guide-grid"><section className="card"><span className="eyebrow">GET STARTED</span><h2>From device signal to coordinated response</h2>
    <ol className="guide-steps">
      <li><h3>Configure your locations</h3><p>Settings holds named locations, optional addresses, rooms and devices. Add input sensors and location-specific virtual outputs. Enable outputs and choose automatic permissions; valve closure always needs confirmation.</p></li>
      <li><h3>Define a simulation</h3><p>In Simulation Studio save a single alert or scenario. Select its initial alarm/connectivity, reporting mode, duration and optional final clear. Saving never triggers an alert.</p></li>
      <li><h3>Start from Command Center</h3><p>Select saved definitions or click a mapped device. Overlap warnings name conflicting definitions. Send schedules a cloud run; it does not mean every signal is published yet. Run status shows expected and published counts.</p></li>
      <li><h3>Let incident coordination run</h3><p>Automatic assignment creates a named incident or joins its related open location/hazard incident. Other properties and unrelated hazards remain separate. Accepted signals share the actual ingestion, assessment and policy pipeline.</p></li>
      <li><h3>Use Alexa+</h3><p>Briefings, active devices and recorded actions refresh automatically. Enable browser speech if wanted. Use bounded status commands, optional notes or explicit action confirmation. No person registry or calling is provided.</p></li>
      <li><h3>Review and resolve</h3><p>History keeps evidence, decisions, notes and old reports. Resolve explicitly closes an incident and cancels associated future generation. A new fresh alert can create a new incident with a fresh simulation allowance.</p></li>
    </ol><button className="primary" onClick={() => navigate('settings')}>Open Settings</button></section>
    <section className="card"><h2>Controls and limits</h2>
      <details open><summary>State, repeats and clear</summary><p>On-change emits the configured state once. Repeat emits active reports at 60–900 second intervals for up to an hour; an optional final clear is separate. The minute-tick worker can deliver late under load, retaining scheduled timestamps. Stop does not clear an alarm. Paused runs may still owe a clear.</p></details>
      <details><summary>Capacity and allowance</summary><p>200 devices across 50 locations, up to 30 devices per room; 250 saved definitions and 2,000 total signal references. One run selects at most 200 distinct devices. Each incident starts with 2,000 reserved simulation signals, extendable deliberately to 10,000. Retries spend once. Exhaustion pauses generation, not the incident or processing of accepted evidence.</p></details>
      <details><summary>Retries and cloud runs</summary><p>Run state persists when the tab closes. Resume reuses pending event identities. Stop releases device ownership; one in-flight delivery may complete. A device cannot belong to overlapping active runs. Existing tab-local pending batches remain retryable for migration.</p></details>
      <details><summary>Map colours and decisions</summary><p>Colours reflect backend current state and a current validated assessment. Multiple distinct smoke detectors can corroborate urgency; repeating one device is not independent corroboration. An urgent indication is not proof of fire size. Proposed, pending, failed and successful virtual actions are distinct.</p></details>
      <details><summary>Fresh evidence and permissions</summary><p>Changed device evidence or notes invalidate old approvals. Policy checks location, permissions, evidence and expiry again at execution. Same-location smoke/CO blocks valve closure, including another open incident. Virtual actions do not control physical devices.</p></details>
      <details><summary>Speech and privacy</summary><p>Speech needs an open browser and permission; microphone support varies. English transcription uses the browser speech service; review before sending. Text is always available. Notes are unverified context, not commands, diagnoses or confirmed occupancy. Draft notes survive reload in this tab.</p></details>
      <details><summary>Edit and delete</summary><p>Settings manages devices and locations. Studio edits/removes reusable definitions without deleting past evidence. Data controls request incident deletion after exact confirmation. A 15-minute drain window precedes scheduled cleanup of records, related runs and all evidence object versions. Only completed means cleaned; minimal replay markers remain. Backups and service history follow separate retention.</p></details>
      <details><summary>Access and safety</summary><p>Sign-in refreshes while your session is valid. A revoked/expired session needs sign-in again. The shared guest account is visible to other visitors: use synthetic data only. This is an incident-coordination prototype, not a safety-certified alarm or emergency service. Follow official alarms and emergency guidance.</p></details>
    </section></div>;
}
